// <auto-generated />
using Deviceflow_ConsoleApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deviceflow_ConsoleApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240403184641_deviceflowclienttable")]
    partial class deviceflowclienttable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("Deviceflow_ConsoleApp.Models.DeviceFlowClientEntity", b =>
                {
                    b.Property<string>("DeviceCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceCode");

                    b.HasIndex(new[] { "DeviceCode" }, "IX_DeviceFlowClients_DeviceCode")
                        .IsUnique();

                    b.ToTable("DeviceFlowClients", "oauthclient");
                });
#pragma warning restore 612, 618
        }
    }
}
